### ISSUE TITLE
story(proof of concept): Lit implementation

### ISSUE THREAD

**Issue by federicoisepponfincons** [lyne-design-system/lyne-components#1831]
### Feature Description

We would like, as proof of concept, to implement some components with lit-element.

e.g. integrate the `time input` component with Lit

### References

https://lit.dev/

### Tasks

- [x] Create new repository
- [x] Implement a few components with lit-element
  - [x] time input component as a native form component (without slotting an input element)
  - [x] a group of components that are tightly coupled (maybe sbb-radio-button and sbb-radio-button-group)
- [ ] Topics to evaluate
  - [x] Getter/Setter
  - [x] Native form support [Example](https://www.dannymoerkerke.com/blog/web-components-can-now-be-native-form-elements/)
  - [x] Lifecycle methods/hooks
  - [x] JSX => html tagged template function
  - [x] Inheritence/Mixins
  - [ ] Hydration (e.g. our .hydrate css rules and SSR)
  - [ ] Support Css in tests ( need to implement a custom plugin for it )
  - [ ] React integration
  - [ ] Distribution format
- [x] Present and discuss findings with the team

**Comment by TomMenga** [comment]
# Storybook migration check-list

* `import type { ... } from '@storybook/html'` => `import type { ... } from '@storybook/web-components'`
* Add the component import - `import { SbbRadioButton } from './sbb-radio-button';`
* Add the creation of an instance - `const a = new SbbRadioButton();`
_Discussion:_ The component instance is necessary for the compiler. Otherwise, the component is stripped by the build.

**Comment by TomMenga** [comment]
# Spec Test migration check-list

TODO
